### ISSUE TITLE
3.2.0-a2 issues

### ISSUE THREAD

**Issue by C1n** [rxu/thanks_for_posts#60]
**When installing the thanks mod (2.3.0-dev) it installs correctly, however when opening the Update counter tab in the ACP I get the following error:**

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The parameter "tables.thanks" must be defined. in /home/blauwwit/domains/blauwwit.be/public_html/beta007/phpBB/cache/production/container_64cd73d669dd8f337d8b1b251fc6bd39.php:3958 Stack trace: #0 /home/blauwwit/domains/blauwwit.be/public_html/beta007/phpBB/ext/gfksx/ThanksForPosts/acp/acp_thanks_refresh_module.php(31): phpbb_cache_container->getParameter('tables.thanks') #1 /home/blauwwit/domains/blauwwit.be/public_html/beta007/phpBB/includes/functions_module.php(676): gfksx\ThanksForPosts\acp\acp_thanks_refresh_module->main('\\gfksx\\ThanksFo...', 'thanks') #2 /home/blauwwit/domains/blauwwit.be/public_html/beta007/phpBB/adm/index.php(81): p_master->load_active() #3 {main} thrown in /home/blauwwit/domains/blauwwit.be/public_html/beta007/phpBB/cache/production/container_64cd73d669dd8f337d8b1b251fc6bd39.php on line 3958

**In addition, when viewing a post with the ACP setting (Thanks Counters on 'yes) it gives the following SQL error:**

SQL ERROR [ mysqli ]

'beta.phpbb_thanks.post_id' isn't in GROUP BY [1055]

SQL

SELECT *, COUNT(poster_id) AS poster_count FROM phpbb_thanks WHERE poster_id IN ('4786', '162', '153', '1360', '3172', '4550', '4370', '3004', '2475', '400', '4630', '2025', '458', '1773', '151', '3700', '4853', '111') AND forum_id <> 49 GROUP BY poster_id

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 999
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/ext/gfksx/ThanksForPosts/core/helper.php
LINE: 752
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/ext/gfksx/ThanksForPosts/event/listener.php
LINE: 182
CALL: gfksx\ThanksForPosts\core\helper->array_all_thanks()

FILE: (not given by php)
LINE: (not given by php)
CALL: gfksx\ThanksForPosts\event\listener->viewtopic_handle_thanks()

FILE: [ROOT]/vendor/symfony/event-dispatcher/EventDispatcher.php
LINE: 181
CALL: call_user_func()

FILE: [ROOT]/vendor/symfony/event-dispatcher/EventDispatcher.php
LINE: 46
CALL: Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 60
CALL: Symfony\Component\EventDispatcher\EventDispatcher->dispatch()

FILE: [ROOT]/phpbb/event/dispatcher.php
LINE: 46
CALL: phpbb\event\dispatcher->dispatch()

FILE: [ROOT]/viewtopic.php
LINE: 1169
CALL: phpbb\event\dispatcher->trigger_event()

**And lastly, when liking a post, subsequently unliking it, I can not re-like the post anymore. I don't get an error, but the page reloads without a like.

**Comment by rxu** [comment]
As for the 1st and 3rd issues, I couldn't reproduce it with phpBB 3.2.0-b2 so far.
As for the 2nd one, that's indeed the extension issue. Will fix it later, thanks.
